site_name: Deep Notes – DeepThinkJo
site_description: Concise textbook-style notes on Mathematics, Computer Science, and
  Artificial Intelligence.
site_url: https://deepthinkjo.github.io/Deep_Notes
docs_dir: notes
theme:
  name: material
use_directory_urls: false
markdown_extensions:
- toc:
    permalink: true
- tables
- admonition
- codehilite
- footnotes
- pymdownx.arithmatex:
    generic: true
- pymdownx.superfences
extra_javascript:
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
- ← Back to DeepThinkJo: https://deepthinkjo.github.io
- Deep Notes:
  - Computer_Science:
    - Python:
      - Chapter 1 – Introduction to Programming and Python:
        - Introduction to Programming and Python: Computer_Science/Python/chapter_1_introduction_to_programming_and_python.md
        - 1.1 Introduction to Computer Engineering: Computer_Science/Python/chapter_1/sec_1_introduction_to_computer_engineering.md
        - 1.2 Introduction to Programming: Computer_Science/Python/chapter_1/sec_2_introduction_to_programming.md
        - 1.3 Introduction to Python: Computer_Science/Python/chapter_1/sec_3_introduction_to_python.md
      - Chapter 2 – Python Programming Basics:
        - Python Programming Basics: Computer_Science/Python/chapter_2_python_programming_basics.md
        - 2.1 Data and Variables: Computer_Science/Python/chapter_2/sec_1_data_and_variables.md
        - 2.2 Basic Data Types: Computer_Science/Python/chapter_2/sec_2_basic_data_types.md
        - 2.3 Operators and Expressions: Computer_Science/Python/chapter_2/sec_3_operators_and_expressions.md
        - 2.4 Input and Output: Computer_Science/Python/chapter_2/sec_4_input_and_output.md
        - 2.5 Control Flow, Conditional Statements: Computer_Science/Python/chapter_2/sec_5_control_flow_conditional_statements.md
        - 2.6 Control Flow, Loops: Computer_Science/Python/chapter_2/sec_6_control_flow_loops.md
        - 2.7 Functions: Computer_Science/Python/chapter_2/sec_7_functions.md
        - '2.8 Error Types and Basic ': Computer_Science/Python/chapter_2/sec_8_error_types_and_basic_exception_handling.md
        - 2.9 Comments and Code Style: Computer_Science/Python/chapter_2/sec_9_comments_and_code_style.md
      - Chapter 3 – Python Data Structures:
        - Python Data Structures: Computer_Science/Python/chapter_3_python_data_structures.md
        - 3.1 Strings: Computer_Science/Python/chapter_3/sec_1_strings.md
        - 3.2 Lists: Computer_Science/Python/chapter_3/sec_2_lists.md
