site_name: Deep Notes â€“ DeepThinkJo
site_description: Concise textbook-style notes on Mathematics, Computer Science, and
  Artificial Intelligence.
site_url: https://deepthinkjo.github.io/Deep_Notes
docs_dir: notes
theme:
  name: material
use_directory_urls: false
markdown_extensions:
- toc:
    permalink: true
- tables
- admonition
- codehilite
- footnotes
- pymdownx.arithmatex:
    generic: true
- pymdownx.superfences
extra_javascript:
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
- Deep Notes:
  - Computer_Science:
    - Python:
      - Introduction to Computer Engineering: notes/Computer_Science/Python/chapter_1/sec_1_introduction_to_computer_engineering.md
      - Introduction to Programming: notes/Computer_Science/Python/chapter_1/sec_2_introduction_to_programming.md
      - Introduction to Python: notes/Computer_Science/Python/chapter_1/sec_3_introduction_to_python.md
      - Introduction to Programming and Python: notes/Computer_Science/Python/chapter_1_introduction_to_programming_and_python.md
      - Data and Variables: notes/Computer_Science/Python/chapter_2/sec_1_data_and_variables.md
      - Basic Data Types: notes/Computer_Science/Python/chapter_2/sec_2_basic_data_types.md
      - Operators and Expressions: notes/Computer_Science/Python/chapter_2/sec_3_operators_and_expressions.md
      - Python Programming Basics: notes/Computer_Science/Python/chapter_2_python_programming_basics.md
  - Misc:
    - General:
      - index: notes/index.md
